version: 2
registries:
  packagist:
    type: composer-repository
    url: "https://repo.packagist.org"
updates:
  - package-ecosystem: "composer"
    directory: "/"
    registries:
      - packagist
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
      - composer
    target-branch: "main"
