---
# Codacy configuration to align with PER 2.0 coding standard
engines:
  # Only use PHP CS Fixer with PER 2.0 standard
  php-cs-fixer:
    enabled: true
    config: .php-cs-fixer.php
  # Disable all other PHP style checkers to avoid conflicts
  phpcodesniffer:
    enabled: false
  phpcs:
    enabled: false
  php-code-sniffer:
    enabled: false
  phpmd:
    enabled: false
  # Keep duplication detection
  duplication:
    enabled: true
    config:
      languages:
        - php

# Exclude non-source files from analysis
exclude_paths:
  - 'vendor/**'
  - '.github/**'
  - 'docker/**'
  - 'node_modules/**'
  - 'tests/Benchmark/**'
  - '*.md'
  - '*.sh'
  - '*.yml'
  - '*.yaml'
  - 'Dockerfile'
  - '.php-cs-fixer.cache'
  - 'composer.lock'
  - 'package-lock.json'
